[versions]
kotlin = "2.3.21"
misk = "2025.12.22.170005-34841c2"
wire = "6.4.7"
flyway = "11.1.0"
jooq = "3.21.2"
mysql-connector = "9.7.0"
spotless = "8.4.0"
commonmark = "0.28.0"
owasp-html-sanitizer = "20240325.1"

[libraries]
misk-bom = { module = "com.squareup.misk:misk-bom", version.ref = "misk" }
misk = { module = "com.squareup.misk:misk" }
misk-actions = { module = "com.squareup.misk:misk-actions" }
misk-config = { module = "com.squareup.misk:misk-config" }
misk-core = { module = "com.squareup.misk:misk-core" }
misk-service = { module = "com.squareup.misk:misk-service" }
misk-inject = { module = "com.squareup.misk:misk-inject" }
misk-prometheus = { module = "com.squareup.misk:misk-prometheus" }
misk-testing = { module = "com.squareup.misk:misk-testing" }
misk-admin = { module = "com.squareup.misk:misk-admin" }
wire-runtime = { module = "com.squareup.wire:wire-runtime" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }
mysql-connector = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector" }
jooq-runtime = { module = "org.jooq:jooq", version.ref = "jooq" }
commonmark = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
owasp-html-sanitizer = { module = "com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer", version.ref = "owasp-html-sanitizer" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
flyway = { id = "net.ltgt.flyway", version = "0.2.0" }
jooq = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
